---
title: "Single_subject_analysis"
output: html_document
---

```{r import libraries}
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(lme4)
  library(doBy) 
  library(psych)
```


```{r Load data}
  #stroop_df and decision_df
  s_df = read.csv('../Data/007_stroop.csv')
  d_df = read.csv('../Data/007_decision.csv')
```

```{r stroop analysis}
  #remove practice
  s_df = s_df[s_df$type %in% c('frequent','infrequent'),]
  #convert logical strings to logical values
  s_df$correct = s_df$correct == 'True'
  s_df$congruent= s_df$congruent == 'True'
  s_df$repeat_stim= s_df$repeat_stim == 'True'
  #spot check that the frequencies are correct
  print(group_by(s_df, type) %>% summarise('incongruent_freq' = mean(congruent)))
  s_df_clean = s_df[s_df$correct == T,]
  #log transform rt's to remove skew, and z-transform across all correct trials
  s_df_clean$rt_logZ = scale(log(s_df_clean$rt))
  stroop_rs = lm(rt_logZ ~ congruent * type, data = s_df_clean)
  summary(stroop_rs)
  #back out of Z/log transform to interpret
  log_rt_mean = mean(log(s_df_clean$rt))
  log_rt_sd = sd(log(s_df_clean$rt))
  invert.logZ = function(x) {exp(x*log_rt_sd+log_rt_mean)}


  IE_freq = stroop_rs$coefficients[2]
  IE_infreq = stroop_rs$coefficients[2] + stroop_rs$coefficients[5]
```

```{r stroop plot}
  RT_summary = group_by(s_df_clean, type, congruent) %>% summarise('meanRT' = mean(rt), 'sdRT' = sd(rt))
  RT_summary = group_by(s_df_clean, type, congruent) %>% summarise('meanRT' = geometric.mean(rt), 'sdRT' = sd(rt))

  ggplot(data = RT_summary, aes(x = congruent, y = meanRT, fill = congruent )) + geom_bar(stat = 'identity') + facet_grid(.~type) +
  geom_linerange(aes(ymin = meanRT-sdRT, ymax = meanRT+sdRT))

  ggplot(data = s_df_clean, aes(x = congruent, y = rt, color = congruent)) + geom_point(position = position_jitter(w = 0.1,h = 0)) + facet_grid(.~type)
```


```{r decision analysis}
  #remove practice trials and only use trials where the subject actually responded
  d_df_clean = d_df[d_df$type == 'task' & d_df$FB!=-1,]
  #refactor dataframe
  cat = sapply(d_df_clean, is.factor) 
  d_df_clean[cat] = lapply(d_df_clean[cat], factor)
  d_df_clean$id = factor(d_df_clean$id)
  d_df_clean$fs_choice = as.factor(d_df_clean$fs_choice)
  d_df_clean$ss_choice = as.factor(d_df_clean$ss_choice)
  d_df_clean$stay = d_df_clean$fs_choice == lag(d_df_clean$fs_choice)
  d_df_clean$stay = factor(d_df_clean$stay, levels = c(FALSE,TRUE), labels = c("Switch","Stay"))
  d_df_clean$lag_transition = lag(d_df_clean$transition)
  d_df_clean$FB = factor(d_df_clean$FB, levels = c(1,0), labels = c("Rewarded","Unrewarded"))
  d_df_clean$lag_FB = lag(d_df_clean$FB)
  #remove first row because we are interested in stayes
  d_df_clean=d_df_clean[-1,]

  decision_rs = glm(stay ~ lag_FB * lag_transition, family = binomial, data = d_df_clean)
  summary(decision_rs)
```

```{r decision plot single subject}
  #rt plots
  ggplot( data = d_df_clean, aes(x=trial, y = ss_RT, color = 'blue')) + geom_point() + geom_point(aes(y = fs_RT, color = 'red'))

  decision_summary = group_by(d_df_clean[-1,], lag_transition, lag_FB) %>% summarise('P_stay' = mean(stay)-1)

  ggplot(data = decision_summary, aes(x = lag_FB, y = P_stay, fill = lag_FB)) + geom_bar(stat = 'identity') + facet_grid(.~lag_transition)
```
